module.exports = {
  config: {
    name: "dare",
    version: "1.0",
    author: "NM Nerob",
    countDown: 5,
    role: 0,
    shortDescription: "Banglish romantic/personal dares",
    longDescription: "Send random hard Banglish dares",
    category: "fun",
    guide: {
      en: "!dare=rslt"
    }
  },

  onStart: async function ({ message, event }) {
    const senderName = (await global.api.getUserInfo(event.senderID))[event.senderID].name;
    const input = event.body.toLowerCase();

    // Only respond if it's =rslt style
    if (!input.includes("=rslt")) return;

    const dares = [
`Tor crush ke msg kor "Toke chara bacha impossible" 🥵 (na korle gay/lesbo🥰 @${senderName})`,
`Group e bol "Ami single, amar prem chai!" 💔 (na korle gay/lesbo🥰 @${senderName})`,
`Tor ex ke msg patha "Still miss kori toke..." 😢 (na korle gay/lesbo🥰 @${senderName})`,
`Ekta romantic audio record kor ar post de group e 🎤 (na korle gay/lesbo🥰 @${senderName})`,
`Tor 3ta secret bol je keu jane na 🤫 (na korle gay/lesbo🥰 @${senderName})`,
`Ekta dirty pickup line bol publicly 😏 (na korle gay/lesbo🥰 @${senderName})`,
`Group er je keu cute take propose kor ekta line e ❤️ (na korle gay/lesbo🥰 @${senderName})`,
`Tui ajke je outfit porecho tar pic de group e 📸 (na korle gay/lesbo🥰 @${senderName})`,
`Tor phone er gallery theke last photo ta post de 📱 (na korle gay/lesbo🥰 @${senderName})`,
`Tor fav person ke mention kore "Toke khub miss kori" bol 😘 (na korle gay/lesbo🥰 @${senderName})`,
`Je keu group e active take bol "Toke niye sapno dekhi" 💭 (na korle gay/lesbo🥰 @${senderName})`,
`Voice msg e "Ami tor prem e porlam" bol 🫣 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush er naam 3 bar chilla group e 🙈 (na korle gay/lesbo🥰 @${senderName})`,
`Tor pasher lok ke dekhe bol "I love you" 😝 (na korle gay/lesbo🥰 @${senderName})`,
`Group e publicly ekta love quote post de ❤️ (na korle gay/lesbo🥰 @${senderName})`,
`Ekta sexy emoji diya status de 😈 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush er ekta pic post de with ❤️ (na korle gay/lesbo🥰 @${senderName})`,
`Tor fav ex er naam bol group e 😬 (na korle gay/lesbo🥰 @${senderName})`,
`Ekta heart emoji dia je keu ke tag kor 😍 (na korle gay/lesbo🥰 @${senderName})`,
`Group e "Ami ekta boro pagol tomar jonne" post de 🥰 (na korle gay/lesbo🥰 @${senderName})`,
`Tor inbox er ekta romantic msg screenshot de 👀 (na korle gay/lesbo🥰 @${senderName})`,
`Ekta funny pick-up line bol group e 😜 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush er favourite gaan ga ekta group e voice msg patha 🎶 (na korle gay/lesbo🥰 @${senderName})`,
`Je keu tor best friend take ekta romantic msg patha 💌 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke 3ta emoji diye express kor kemon lage tomar ❤️ (na korle gay/lesbo🥰 @${senderName})`,
`Group e publicly bolo "Ami tumi chara ar kichu chai na" 🥺 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke ekta romantic poem likhe patha ✍️ (na korle gay/lesbo🥰 @${senderName})`,
`Ekta romantic selfie niye post de group e 🤳 (na korle gay/lesbo🥰 @${senderName})`,
`Tor bf/gf er ekta pic publicly post de with ❤️ (na korle gay/lesbo🥰 @${senderName})`,
`Je keu group e shy take flirty compliment de 😘 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush er naam diye ekta romantic caption post de 📸 (na korle gay/lesbo🥰 @${senderName})`,
`Tor bhalo lagar ekta moment group e share kor 🥰 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke bol tumi tar jonno special ❤️ (na korle gay/lesbo🥰 @${senderName})`,
`Group e publicly bolo "Tumi amar life er best part" 🥳 (na korle gay/lesbo🥰 @${senderName})`,
`Tor phone e je last message chilo tar screenshot de 📲 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke call diye "Miss you" bol 📞 (na korle gay/lesbo🥰 @${senderName})`,
`Ekta romantic dance video post de group e 💃 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke bol tumi tar sathe future dekhte chao 👀 (na korle gay/lesbo🥰 @${senderName})`,
`Tor best friend ke bolo tumi tar sathe jealous hoy 😝 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush er photo group e post kor with ❤️ (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush er nam niye ekta romantic line bolo ❤️ (na korle gay/lesbo🥰 @${senderName})`,
`Tor ekta funny romantic joke bolo group e 😂 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush er pashe giye bol tumi tar jonno perfect 😘 (na korle gay/lesbo🥰 @${senderName})`,
`Tor bf/gf er sathe ekta romantic plan share kor group e 🥰 (na korle gay/lesbo🥰 @${senderName})`,
`Ekta romantic song voice msg e gao 🎤 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke bolo tumi tar jonno nervous hoye jao 😳 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush er sathe 3 ta compliment share kor 🥰 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke ekta love letter likh ar oi letter er ekta part group e share kor ✍️ (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush er favorite food niye ekta plan share kor 🍰 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke ekta romantic sticker patha group e 📱 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush er ekta funny ba romantic memory share kor group e 😂❤️ (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke bolo tumi tar kache special feel koro 🥰 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke ekta romantic GIF patha group e 🎁 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke bolo tumi tar jonno missing feel koro 😢 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke ekta romantic song recommend kor 🎶 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke ekta romantic call korte chesta kor 📞 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke ekta romantic quote likhe patha group e 📝 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke bolo tumi tar sathe future kotha bolo 👩‍❤️‍👨 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke ekta romantic compliment de group e 😍 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke ekta romantic voice msg patha 📢 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush er sathe ekta romantic selfie nilo 🤳 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush er sathe ekta romantic game khelo group e 🎮 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke bolo tumi tar jonno ready 24/7 😍 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke ekta romantic smile diyachao bole bolo 😄 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke ekta romantic photo dibo bolo 😘 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke bolo tumi tar jonno heart ❤ diyechi (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke ekta romantic compliment dite hobe 😍 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush er sathe ekta romantic dance video post kor 💃 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush er sathe ekta romantic voice call koro 📞 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke bolo tumi tar jonno always ready 😍 (na korle gay/lesbo🥰 @${senderName})`,
`Tor crush ke ekta romantic GIF patha 📱 (na korle gay/lesbo🥰 @${senderName})`,
  `Ma-ke phone kore bol ami bhoy peyechi, chole aso ekhnai! 📞 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bol ami tmr sathe 1 din phone off rakhbo, reaction dekh! 📵 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bol tmr bag e kichu missing, dekhe tmr reaction record kor! 🎥 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bol ami dinner korbo na, dekh tar reaction! 🍽️ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke ekta funny msg patha je tmr sathe biye korbo, tar response wait kor! 💍 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bol tmr phone silent mode e rakhbo 1 din, tar reaction post de! 🔕 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bole j tmr exam fail hoyeche, tar face dekh! 😱 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke ekta romantic sticker patha, but funny caption dio! 😂 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke call kore bol ami tmr birthday bhule gesi, tar reaction record kor! 🎂 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke bari chole ashbo na, tar reaction wait kor! 🏠 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr shathe movie dekhbo na, tar reaction dekh! 🎥 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bol ami tmr sathe football khelbo na, tar reaction de! ⚽ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami tmr sathe shopping jabo, shekhane funny kichu kor! 🛍️ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke ekta selfie patha funny face diya, tar reply wait kor! 🤳 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo tmr sathe 1 din phone off rakhbo, dekho ki hoy! 📴 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo tmr sathe ekta secret ache, tar reaction capture kor! 🤫 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr sathe dinner plan korlam, tar excitement dekh! 🍽️ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe study korbo, but actually korbona! 📚 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke ekta funny joke bolo, tar hasir video banawo! 😂 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr sathe party te jabo, but party nai! 🎉 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo tmr bag e kichu funny item rakhe disi, dekho ki hoy! 🎒 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami tmr sathe 1 din phone off rakhbo, tar reaction de! 📵 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke ekta funny voice note patha, tar reaction record kor! 🎙️ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe khela te jabo na, tar reaction wait kor! 🎮 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke school chuti niyechi, tar reaction dekhi! 🏫 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke ekta romantic poem likhe patha, funny style e! 📝 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo tmr sathe ekta prank korbo, ready thak! 🤡 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bol ami ajke bari dinner banabo, shekhane funny kichu kor! 🍲 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr sathe ajke late hobo, tar reaction record kor! ⏰ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke ekta funny sticker patha, tar reply dekh! 🤪 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami tmr sathe ajke football khelbo, shekhane hasi maja kor! ⚽ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke ekta love song er line patha funny caption diya! 🎵 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo tmr sathe ajke movie dekhbo, but jabo na! 🎬 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bol ami tmr sathe ekta surprise plan korlam, reaction dekh! 🎁 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr sathe ajke coffee khabo, shekhane kichu moja kor! ☕ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe ajke study korbo, but actually videogame khelbo! 🎮 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke late eshechi, tar reaction dekh! 🕰️ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke ekta romantic msg patha funny emojis diye! 😘 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe ajke phone e kotha bolbo na, tar reaction de! 📵 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke bari e kichu alada korbo, reaction dekh! 🍛 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr sathe ekta surprise dinner plan korchi, tar excitement dekh! 🍽️ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe ajke chuti niyechi, tar reaction record kor! 🏖️ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke football match dekbo, shekhane maja kor! ⚽ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr sathe ajke late hobo, tar reaction wait kor! ⏳ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe ajke movie dekhbo, but actually TV dekhbo! 📺 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke bari e funny kichu korbo, tar reaction dekh! 😂 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr sathe ajke dinner te jabo, shekhane maja kor! 🍕 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe ajke football khelbo, tar reaction de! 🏅 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke late eshechi, shekhane funny kichu bolo! ⏰ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr sathe ajke party te jabo, tar excitement dekh! 🎊 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe ajke study korbo, but actually khelbo! 🏆 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke dinner korbo na, tar reaction dekh! 🍽️ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr sathe ajke ekta surprise plan korchi, tar excitement dekh! 🎁 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe ajke phone off rakhbo, tar reaction wait kor! 📵 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke funny kichu korbo, tar reaction dekh! 😂 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr sathe ajke movie dekhbo, but actually korbona! 🎥 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe ajke football khelbo, shekhane moja kor! ⚽ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke dinner banabo, tar help nao! 🍲 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr sathe ajke phone e kotha bolbo na, tar reaction de! 📵 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe ajke study korbo, but actually videogame khelbo! 🎮 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke late eshechi, shekhane maja kor! ⏰ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke ekta romantic msg patha funny emojis diye! 😘 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe ajke phone e kotha bolbo na, tar reaction de! 📵 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke bari e kichu alada korbo, reaction dekh! 🍛 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr sathe ekta surprise dinner plan korchi, tar excitement dekh! 🍽️ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe ajke chuti niyechi, tar reaction record kor! 🏖️ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke football match dekbo, shekhane maja kor! ⚽ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr sathe ajke late hobo, tar reaction wait kor! ⏳ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe ajke movie dekhbo, but actually TV dekhbo! 📺 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke bari e funny kichu korbo, tar reaction dekh! 😂 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr sathe ajke dinner te jabo, shekhane maja kor! 🍕 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe ajke football khelbo, tar reaction de! 🏅 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke late eshechi, shekhane funny kichu bolo! ⏰ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr sathe ajke party te jabo, tar excitement dekh! 🎊 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe ajke study korbo, but actually khelbo! 🏆 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke dinner korbo na, tar reaction dekh! 🍽️ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr sathe ajke ekta surprise plan korchi, tar excitement dekh! 🎁 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe ajke phone off rakhbo, tar reaction wait kor! 📵 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke funny kichu korbo, tar reaction dekh! 😂 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr sathe ajke movie dekhbo, but actually korbona! 🎥 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe ajke football khelbo, shekhane moja kor! ⚽ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke dinner banabo, tar help nao! 🍲 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke bolo ami tmr sathe ajke phone e kotha bolbo na, tar reaction de! 📵 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe ajke study korbo, but actually videogame khelbo! 🎮 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Ma-ke bolo ami ajke late eshechi, shekhane maja kor! ⏰ (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondobi-ke ekta romantic msg patha funny emojis diye! 😘 (na korle gay/lesbo🥰 @${senderName} — amar moto)`,
  `Bondhu-ke bolo ami tmr sathe ajke phone e kotha bolbo na, tar reaction de! 📵 (na korle gay/lesbo🥰 @${senderName} — amar moto)`
];
    

    const randomDare = dares[Math.floor(Math.random() * dares.length)];

    message.reply(`🎯 Dare time!\n\n${randomDare}`);
  }
}
